export TERM=xterm-256color
# Path to your oh-my-zsh installation.
export ZSH=/home/penguinrage/.oh-my-zsh
export AWS_ACCESS_KEY_ID=''
export AWS_SECRET_ACCESS_KEY=''



if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="ys"
ZSH_THEME="agnoster"
#ZSH_THEME="bullet-train"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(autojump git pep8 ruby arch colored-man extract web-search)

# User configuration

# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"
export PATH="/home/penguinrage/.gem/ruby/2.3.0/bin:/home/penguinrage/anaconda3/bin:$PATH"

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

r=$(($RANDOM%4))
if [ $r -eq 0 ]; 
then 
    LS_COLORS=$LS_COLORS:'di=0;32:' ; export LS_COLORS
elif [ $r -eq 1 ]; 
then 
    LS_COLORS=$LS_COLORS:'di=0;36:' ; export LS_COLORS
elif [ $r -eq 2 ]; 
then 
    LS_COLORS=$LS_COLORS:'di=0;34:' ; export LS_COLORS
else
    LS_COLORS=$LS_COLORS:'di=0;35:' ; export LS_COLORS
fi

# Aliases
alias weather='curl -4 wttr.in/Sydney > weather.txt && cat weather.txt | head -n 37'
alias mySignal="iwconfig wlp2s0 | grep -i --color quality"
alias gg="gdb -tui"
alias diff='colordiff'
## pass options to free ## 
alias meminfo='free -m -l -t'
alias vlive='source venv/bin/activate'
# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
   
## Get server cpu info ##
alias cpuinfo='lscpu'
   
alias diff='colordiff'

alias elastic_start='systemctl start elasticsearch'
alias elastic_stop='systemctl stop elasticsearch'
alias ghistory='git log --graph --oneline --all'
## Common cd locations
alias COMP3109='cd ~/Dropbox/UNI/COMP3109'
alias ELEC3609='cd ~/Dropbox/UNI/ELEC3609'
alias COMP3615='cd ~/Dropbox/UNI/COMP3615'
alias INFO3406='cd ~/Dropbox/UNI/INFO3406'
alias postlive='sudo systemctl start postgresql'

## Antlr4
alias grun='java org.antlr.v4.runtime.misc.TestRig'
export CLASSPATH=".:/usr/local/lib/antlr-4.5.3-complete.jar:$CLASSPATH"
alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.5.3-complete.jar:$CLASSPATH" org.antlr.v4.Tool'

## get GPU ram on desktop / laptop## 
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
